version: '3.8'

services:

  # DB service
  db:
    image: mongo:7.0.2
    restart: unless-stopped

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

    volumes:
    - ${DB_DATA}:/data/db
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    ports:
      - ${DB_PORT}:27017

    networks:
      - db-api-net

networks:
  # Network for DB and API
  db-api-net:
    external: true
    name: db-api