version: '3.8'

services:

  # API service
  api:
    image: "rain-simulator-api:latest"
    container_name: rain-simulator-api
    restart: unless-stopped

    command: sh -c "poetry run python /api/api.py"

    build:
      context: ./api

    networks:
      - backend

  # Nginx reverse proxy service
  nginx:
    image: "rain-simulator-nginx:latest"
    container_name: rain-simulator-nginx
    restart: unless-stopped

    build:
      context: ./nginx

    command: sh -c "nginx -g 'daemon off;'"

    ports:
      - ${NGINX_PORT}:8000

    depends_on:
      api:
        condition: service_started

    networks:
      - backend
  
# Set networks
networks:
  backend:
    driver: bridge