version: '3.8'

services:

  # API service
  api:
    image: "rain-simulator-api:latest"
    container_name: rain-simulator-api
    restart: unless-stopped

    command: sh -c "poetry run python /api/api.py"

    build:
      context: ./api

    environment:
      - API_CONFIG=${API_CONFIG}
      - API_PREFIX=${API_PREFIX}
      - API_DB_CONNECTION_STRING=${API_DB_CONNECTION_STRING}
      - API_DB_MIN_POOL_SIZE=${API_DB_MIN_POOL_SIZE}
      - API_DB_MAX_POOL_SIZE=${API_DB_MAX_POOL_SIZE}
      - API_DB_SERVER_SELECTION_TIMEOUT_MS=${API_DB_SERVER_SELECTION_TIMEOUT_MS}
      - API_DB_MAX_IDLE_TIME_MS=${API_DB_MAX_IDLE_TIME_MS}

    networks:
      - backend
      - db-api

  # Nginx reverse proxy service
  nginx:
    image: "rain-simulator-nginx:latest"
    container_name: rain-simulator-nginx
    restart: unless-stopped

    build:
      context: ./nginx

    command: sh -c "nginx -g 'daemon off;'"

    ports:
      - ${NGINX_PORT}:8000

    depends_on:
      api:
        condition: service_started

    networks:
      - backend
  
# Set networks
networks:
  # Nginx and API services network
  backend:
    driver: bridge
  # Distributed API and DB network
  db-api:
    external: true
    name: rainsim-db-api
  
