version: '3.8'

services:

  # DB service
  db:
    image: mongo:7.0.2

    volumes:
    - ${DB_DATA}:/data/db
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    ports:
      - ${DB_PORT}:27017

    networks:
      - db-api

networks:
  # Distributed API and DB network 
  db-api:
    external: true
    name: rainsim-db-api